name: vlm_wm # You can change this environment name if you like
channels:
  - defaults
  - conda-forge
  # - pytorch # Add this channel if you prefer to install PyTorch via conda, especially for specific CUDA versions
dependencies:
  # ===== Conda packages =====
  # These are generally cross-platform. Conda will fetch Linux versions.
  - python=3.9
  - ca-certificates
  - openssl
  - pip
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  # For GPU support with PyTorch installed via Conda, you might add:
  # - cudatoolkit=11.3 # Example: ensure this matches your PyTorch version's CUDA requirement

  # ===== Pip packages =====
  - pip:
    # Install your local packages in editable mode
    # Ensure these paths are correct relative to where this YAML file is located
    # (e.g., if this file is in Dissertation/, and atari_gpt is Dissertation/atari_gpt/)
    - -e ./atari_gpt
    - -e ./iris
    # - -e ./vlm_world_model # If vlm_world_model itself were also a package

    # General Python package dependencies:
    - ale-py==0.8.1
    - annotated-types==0.6.0
    - anthropic==0.25.7
    - anyio==4.3.0
    - autorom==0.4.2
    - autorom-accept-rom-license==0.6.1
    - cachetools==5.3.3
    - certifi==2024.2.2 # Version from your list, can be updated by conda/pip if needed
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - contourpy==1.2.1
    - cycler==0.12.1
    - decorator==4.4.2 # Older version, might be a transitive dependency requirement
    - distro==1.9.0
    - einops==0.3.2
    - exceptiongroup==1.2.1
    - farama-notifications==0.0.4
    - filelock==3.14.0
    - fonttools==4.53.1
    - fsspec==2024.3.1
    - google-ai-generativelanguage==0.6.2
    - google-api-core==2.19.0
    - google-api-python-client==2.127.0
    - google-auth==2.29.0
    - google-auth-httplib2==0.2.0
    - google-generativeai==0.5.2
    - googleapis-common-protos==1.63.0
    - groq==0.5.0
    - grpcio==1.63.0
    - grpcio-status==1.62.2
    - gymnasium==0.29.1
    - h11==0.14.0
    - httpcore==1.0.5
    - httplib2==0.22.0
    - httpx==0.27.0
    - huggingface-hub==0.22.2
    - hydra-core==1.1.1
    - idna==3.7
    - imageio==2.34.2
    - imageio-ffmpeg==0.5.1
    - importlib-metadata==8.2.0 # Required for python <3.10 for some packages
    - importlib-resources==6.4.0 # Required for python <3.9 by some packages
    - kiwisolver==1.4.5
    - matplotlib==3.9.1.post1
    - moviepy==1.0.3
    - numpy==1.26.4
    - openai==1.25.0
    - opencv-python==4.9.0.80
    - packaging==24.0
    - pillow==10.4.0
    - proglog==0.1.10
    - proto-plus==1.23.0
    - protobuf==4.25.3
    - psutil==5.8.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pydantic==2.7.1
    - pydantic-core==2.18.2
    - pygame==2.6.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.1
    - requests==2.31.0
    - rsa==4.9
    - shimmy==0.2.1
    - six==1.16.0
    - sniffio==1.3.1
    - tokenizers==0.19.1
    - tqdm==4.66.2
    - typing-extensions==4.11.0 # Often needed for newer type hints on older Python
    - uritemplate==4.1.1
    - urllib3==2.2.1
    - wandb==0.12.7
    - zipp==3.19.2 # Often a dependency for importlib-metadata or importlib-resources
    - torch==1.11.0
    - torchvision==0.12.0
    - transformers # No version specified, pip will get the latest or as per other dependencies