# Overall system configuration
system:
  seed: 42
  log_level: INFO
  log_dir: "logs/"
  real_time_render: True
  live_chat: True   # Enable/disable the live chat window alongside rendering

# VLM Planner settings (based on atari_gpt)
vlm:
  # Model settings
  model_key: "gpt4o"  # Options: gpt4, gpt4o, claude, gemini, qwen
  model_name: "gpt-4o"  # Specific model name
  temperature: 1.0
  use_world_model: True
  
  # Planning configuration
  num_plans: 3       # Number of alternative plans to generate
  plan_horizon: 5   # How many steps ahead to plan
  action_placeholders: "action1, action2, ..., action{plan_horizon}"  # Will be formatted at runtime
  plan_placeholders: ",...more plans up to {num_plans} total..."      # Will be formatted at runtime

  # Action buffer configuration
  use_action_buffer: True   # Enable/disable the action buffer
  action_buffer_size: 10    # Maximum number of plans to store in the buffer
  action_buffer_threshold: 0.0  # Minimum score required for a plan to be stored

  system_prompt: >
    ${sys_prompt.system_prompt}

defaults:
  - _self_
  - tokenizer: default
  - world_model: default
  - sys_prompt: Breakout


common:
  device: cpu
  sequence_length: ${world_model.max_blocks}


# Environment settings
environment:
  name: "Breakout"     # Gym environment name
  num_timesteps: 1000  # Maximum number of timesteps to run the environment for


# Paths and integration settings
paths:
  atari_gpt_path: ${hydra:runtime.cwd}/atari_gpt
  iris_path: ${hydra:runtime.cwd}/iris
  results_dir: "results/"
  checkpoint_dir: "checkpoints/"

# Evaluation settings
evaluation:
  models: ["gpt4o"]  # List of models to evaluate, use ["all"] for all models